### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
- Use another speedtest.net source to get it run again
- Add linter process and lint code
- Cleanup and update dependencies
- Drop local jquery and justgage files
- Format README

### CODE REVIEW

**Comment by BrianHepler** [comment]
I gave your PR a test run and everything looks great. Thank you for doing this.

**Comment by KristjanESPERANTO** [comment]
You're welcome. Thank you for taking over the module from ronny3050 and taking care of it!
 :smiley:

**Comment by BrianHepler** [comment]
Urrrrgh. I haven't taken over the module. I just occasionally fix it when it's broken. It started off on a whim just to see if I could figure out what was wrong. But between the two of us we can probably keep it limping along.

**Comment by KristjanESPERANTO** [comment]
Okay, that's fine with me :slightly_smiling_face:

**Pull request merged**
